name: check_bloc
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  go_router: ^6.2.0
  equatable: ^2.0.5
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  http: ^0.13.5
  intl: ^0.18.0
  flutter_secure_storage: ^8.0.0
  json_annotation: ^4.8.0
  shared_preferences: ^2.0.20
  dartz: ^0.10.1
  share_plus: ^6.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.6.1
  build_runner: ^2.3.3

flutter:
  uses-material-design: true

